Database
Cascadia-Connections/suite-career-web-api pull request #3
Opened 2023-04-21 02:19 UTC by darthcod3r

DbContext is configured and initial migration has been added!

2023-04-21 17:24 UTC, Chadloswald approved these changes, later dismissed
I'm not sure exactly what I'm looking at, but I aprove

2023-04-21 22:24 UTC, Bansenauer-Cascadia requested changes
The original develop branch had some files included that we don't need to track in the repository (they are generated on our individual machines.) Please  fix this in your branch and repush

1. be sure your terminal is in the root directory (the directory with the README.md file). Use `ls` to check and `cd ..` to move up one directory until you get to the root
2. change to your directory to the solutions folder `cd SuiteCareers/`
3. run the following commands one after another to clear your git tracking cache

```
git rm -r --cached SuiteCareers/app.db
git rm -r --cached SuiteCareers/.DS_Store
git rm -r --cached SuiteCareers/.vs/.
git rm -r --cached SuiteCareers/bin/.
git rm -r --cached SuiteCareers/obj/.
git commit -m "updates cache"
```

2023-04-21 22:24 UTC, Bansenauer-Cascadia commented on SuiteCareers/SuiteCareers/Models/Response.cs
> +        public int questionId { get; set; }
To stay with C# standards, ALL properties in model classes should use CamelCase with the first letter capitalized

2023-04-21 22:24 UTC, Bansenauer-Cascadia commented on SuiteCareers/SuiteCareers/Models/User.cs
> +        public long Id { get; set; }
For consistency, name this key `UserId`

2023-04-21 22:24 UTC, Bansenauer-Cascadia commented on SuiteCareers/SuiteCareers/Models/User.cs
> +        [Key, DataType(DataType.EmailAddress)]
Though email is unique, I recommend using a separate, dedicated Id field `UserId`

To guarantee that an email can't be used twice in the database use the Unique annotation
```
[Index(IsUnique=true)]
[DataType(DataType.EmailAddress)]
```

2023-04-21 22:53 UTC, Bansenauer-Cascadia commented on SuiteCareers/SuiteCareers/Models/User.cs
> +        public long Id { get; set; }
Also make it a `[Key]`

2023-04-26 21:05 UTC, ParkerW98 approved these changes, later dismissed
great work with this Noah

2023-04-26 21:45 UTC, Bansenauer-Cascadia requested changes
Some updates needed still

2023-04-26 21:45 UTC, Bansenauer-Cascadia commented on SuiteCareers/SuiteCareers/obj/SuiteCareers.csproj.nuget.dgspec.json
> +{
This entire `obj` folder should be deleted from the repository, along with the  `SuiteCareers.db-shm` and `SuiteCareers.db-wal` files. You also may need to clear your cache of them, e.g.,  `git rm --cached SuiteCareers.db-shm`

2023-04-26 21:45 UTC, Bansenauer-Cascadia commented on SuiteCareers/SuiteCareers/Models/User.cs
> +        [Required(ErrorMessage = "Please Enter the state of which you live")]
These error message don't make any sense in the Entity model, only in a ViewModel. 
Just use the `[Required]` notation to avoid confusion

2023-04-27 21:15 UTC, tylerjacobwilson approved these changes
Looks good

2023-04-27 21:40 UTC, snholmes approved these changes
All is working on my end.

2023-04-27 22:12 UTC, ParkerW98 approved these changes
Most recent changes work well and look good!

2023-04-27 22:14 UTC, Bansenauer-Cascadia approved these changes

2023-04-27 22:14 UTC, merged